export const XUBIE_DATA = {
  company: {
    name: "Xubie Snacks",
    legalName: "Xuliani LLC",
    dba: "Xubie Snacks",
    founded: 2026,
    location: "2095 Fruitdale Avenue, San Jose, CA 95128",
    zelle: "(408) 849-6090",
    whatsapp: "14086796016",
    whatsappDisplay: "1 (408) 679-6016",
    cashapp: "$XULANIN7",
    cashappLink: "https://cash.app/$XULANIN7",
    email: "xubiesnacks@yahoo.com",
    website: "https://xulanin.com",
    instagram: "https://www.instagram.com/xubie_snacks",
    tiktok: {
      url: "https://www.tiktok.com/@xubiesnacks",
      handle: "@xubiesnacks",
      stats: {
        videos: 47,
        followers: 577,
        likes: 4722,
        following: 453,
      },
    },
    tagline: "Snacks That Smack",
    orderCutoff: "8pm",
    pickupTime: "15–30 min",
    mission:
      "Handcrafted sweets and treats rooted in community, built for DM-to-order pickup, local delivery, and unforgettable Bay Area pop-ups.",
    story:
      "Xubie Snacks grew out of Nina Lux's entrepreneurial journey at the School of AI and quickly became a real-world Bay Area brand. The booth, the spin wheel, the menu boards, the merch, the QR codes, the pudding cups, and the Xubie Cake all work together to create a joyful experience that feels alive before the first bite. Every pop-up is part bakery, part community gathering, and part proof that a student founder can build something magnetic in public.",
    stats: {
      posts: 29,
      followers: 614,
      tiktokFollowers: 577,
      tiktokVideos: 47,
      tiktokLikes: 4722,
      popUps: 25,
      approval: 100,
    },
  },
  founder: {
    name: "Nina Lux",
    title: "Founder & Chief Snack Officer",
    bio: "Nina Lux is a student entrepreneur studying entrepreneurship and human flourishing at the School of AI. Through Xuliani LLC, she turned Xubie Snacks into a living brand with real booths, returning customers, social proof, and a visual identity people instantly recognize. With mentorship from Dr. Freedom Cheteni and product support from Devin and Xuliani, Nina is building a business that feels both community-first and internet-native.",
    professor: "Dr. Freedom Cheteni",
    engineer: "Devin (AI Software Engineer)",
    school: "School of AI (sof.ai)",
    agent: "Xuliani",
  },
  products: [
    {
      id: 1,
      name: "Banana Pudding",
      description:
        "Creamy, layered, and instantly recognizable from the booth. The cup that keeps showing up in reaction videos and repeat orders.",
      priceReg: 8,
      priceLrg: 12,
      tags: ["bestseller", "crowd-favorite"],
      image: "/branding/community-closeup.jpeg",
      emoji: "🍮",
      accentFrom: "from-amber-500",
      accentTo: "to-yellow-400",
      accentHex: "#f59e0b",
      gradientOverlay: "from-amber-900/75 via-amber-900/20 to-transparent",
      ingredients: ["Fresh Bananas", "Vanilla Wafers", "House Cream", "Homemade Custard"],
      servingReg: "Solo · ~12 oz",
      servingLrg: "Serves 2–3 · ~24 oz",
      reviewSnippet: "Keeps showing up in everyone's reaction videos",
      weeklyOrders: 47,
      sizes: [
        { name: "Regular", size: "reg" as const, price: 8, serving: "Solo · ~12 oz" },
        { name: "Large", size: "lrg" as const, price: 12, serving: "Serves 2–3 · ~24 oz" },
      ],
    },
    {
      id: 2,
      name: "Biscoff Banana Pudding",
      description:
        "The fan-favorite upgrade — classic banana pudding layered with Biscoff cookie crumble and caramel drizzle for an irresistible twist.",
      priceReg: 9,
      priceLrg: 13,
      tags: ["bestseller", "new"],
      image: "/branding/community-hero.jpeg",
      emoji: "🍪",
      accentFrom: "from-orange-600",
      accentTo: "to-amber-500",
      accentHex: "#ea580c",
      gradientOverlay: "from-orange-950/75 via-orange-900/20 to-transparent",
      ingredients: ["Biscoff Crumble", "Caramel Drizzle", "Fresh Bananas", "House Cream"],
      servingReg: "Solo · ~12 oz",
      servingLrg: "Serves 2–3 · ~24 oz",
      reviewSnippet: "The Biscoff twist that made everyone order twice",
      weeklyOrders: 38,
      sizes: [
        { name: "Regular", size: "reg" as const, price: 9, serving: "Solo · ~12 oz" },
        { name: "Large", size: "lrg" as const, price: 13, serving: "Serves 2–3 · ~24 oz" },
      ],
    },
    {
      id: 3,
      name: "Xubie Cake",
      description:
        "The namesake dessert with full brand energy — soft, sweet, and built to make first-time tasters believers.",
      priceReg: 6,
      priceLrg: 14,
      tags: ["signature"],
      image: "/branding/community-side.jpeg",
      emoji: "🎂",
      accentFrom: "from-rose-500",
      accentTo: "to-pink-400",
      accentHex: "#f43f5e",
      gradientOverlay: "from-rose-950/75 via-rose-900/20 to-transparent",
      ingredients: ["Signature Cake Layers", "House Frosting", "Fresh Filling"],
      servingReg: "1 generous slice",
      servingLrg: "4 slices · party-ready",
      reviewSnippet: "The dessert you try once and immediately tell everyone about",
      weeklyOrders: 29,
      sizes: [
        { name: "Regular", size: "reg" as const, price: 6, serving: "1 generous slice" },
        { name: "Large", size: "lrg" as const, price: 14, serving: "4 slices · party-ready" },
      ],
    },
  ],
  bundle: {
    name: "The Xubie Trio",
    description: "One of everything — the ultimate Xubie experience",
    tagline: "Discover your favorite in one order",
    priceReg: 23,
    priceLrg: 39,
    savingsReg: 0,
    savingsLrg: 0,
    emoji: "🎉",
  },
  testimonials: [
    {
      name: "Lake Merritt customer",
      text: "We came for one cup and left talking about Xubie the whole way home. The booth felt alive and the banana pudding absolutely delivered.",
      rating: 5,
      product: "Banana Pudding",
    },
    {
      name: "Snack Sundays regular",
      text: "Xubie Cake is the kind of dessert you try once and immediately start telling other people about. The branding pulled us in and the flavor closed the deal.",
      rating: 5,
      product: "Xubie Cake",
    },
    {
      name: "Bay Area pop-up guest",
      text: "The whole table looked premium — merch, menu board, samples, QR code, all of it. It felt like a real brand, not a temporary booth.",
      rating: 5,
      product: "Biscoff Banana Pudding",
    },
    {
      name: "Parent at the booth",
      text: "You know it's good when the kids like it. We tried the desserts first and ended up following the page before we even left.",
      rating: 5,
      product: "Banana Pudding",
    },
    {
      name: "Event host",
      text: "Xubie brought energy, not just food. The sweets-and-treats setup made our event feel warmer and way more memorable.",
      rating: 5,
      product: "Xubie Cake",
    },
    {
      name: "Instagram follower",
      text: "The reels convinced me to order and the real thing was even better. You can feel that this brand is being built with intention.",
      rating: 5,
      product: "Biscoff Banana Pudding",
    },
  ],
  faqs: [
    {
      q: "How do I order?",
      a: "You can order directly through the site, chat with Xulanin (our AI concierge), send a WhatsApp message to 1 (408) 679-6016, or DM @xubie_snacks on Instagram. If you already know what you want, WhatsApp is the fastest path.",
    },
    {
      q: "Do you offer pickup or delivery?",
      a: "Yes! Pickup is always free from our San Jose location (15–30 min). We also deliver across the Bay Area: South Bay ($3.99), Peninsula ($5.99), East Bay ($7.99), and SF/North Bay ($9.99). Estimated delivery times vary by zone.",
    },
    {
      q: "What fees are there?",
      a: "We keep it transparent! There's a 5% service fee (capped at $5), a $2 small order fee on orders under $15, and CA sales tax (9.375%). Delivery fees depend on your zone. Pickup is always free. Tips are optional but appreciated!",
    },
    {
      q: "What sizes are available?",
      a: "All items come in Regular and Large sizes. Regular is perfect for one person, while Large is great for sharing or when you know you want more.",
    },
    {
      q: "How do I pay?",
      a: "We accept CashApp ($XULANIN7), Zelle, and cash at pop-ups. Payment details are confirmed when you place your order via WhatsApp or the site.",
    },
    {
      q: "Do you cater events or pop-ups?",
      a: "Absolutely. Xubie can prepare dessert trays, tasting tables, and custom event spreads for birthdays, community events, creator gatherings, and brand activations.",
    },
    {
      q: "What is Xulanin?",
      a: "Xulanin is the AI concierge behind the brand. It helps answer menu questions, guide orders, support customers, and keep the digital experience feeling as responsive as the real booth.",
    },
    {
      q: "Can I preorder for a specific date?",
      a: "Yes. Preorders are ideal for larger orders, pop-up pickup, and custom event requests. Message us via WhatsApp or the contact form with your preferred date and quantities.",
    },
    {
      q: "Who is behind Xubie Snacks?",
      a: "Xubie Snacks is founded by Nina Lux through Xuliani LLC. The venture is being built at the School of AI with guidance from Dr. Freedom Cheteni and engineering support from Devin.",
    },
  ],
  howItWorks: [
    {
      step: 1,
      title: "Pick Your Favorites",
      description:
        "Browse our three signature treats — Banana Pudding, Biscoff Banana Pudding, and Xubie Cake — in Regular or Large.",
    },
    {
      step: 2,
      title: "Send Your Order",
      description:
        "Chat with Xulanin, message us on WhatsApp at 1 (408) 679-6016, or DM @xubie_snacks on Instagram.",
    },
    {
      step: 3,
      title: "Fresh Prep Begins",
      description:
        "Each order is assembled with the same visual care and flavor focus that shows up at the booth and across the Instagram page.",
    },
    {
      step: 4,
      title: "Pick Up or Get It Delivered",
      description:
        "Grab it in San Jose, arrange local delivery, or catch Xubie live at the next Bay Area pop-up. Pay via CashApp ($XULANIN7).",
    },
  ],
  deliveryZones: [
    { name: "South Bay", cities: "San Jose, Santa Clara, Sunnyvale", fee: 3.99 },
    { name: "Peninsula", cities: "Palo Alto, Menlo Park, Redwood City", fee: 5.99 },
    { name: "East Bay", cities: "Oakland, Berkeley, Fremont", fee: 7.99 },
    { name: "SF / North Bay", cities: "San Francisco, Marin, Sausalito", fee: 9.99 },
  ],
};
